app = "emocoes"

[build]
  dockerfile = "dockerfile"
  context = "."

[env]
  PORT = "8080"
  DJANGO_DEBUG = "False"
  ALLOWED_HOSTS = "emocoes.fly.dev,localhost"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    protocol = "http"
    method = "GET"
    path = "/healthz"
    interval = "10s"
    timeout = "2s"
    grace_period = "10s"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1



