app = "mix-and-match"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = "30s"
    timeout = "10s"
    method = "get"
    path = "/api/health/"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1