name: Deploy no Fly.io
on: 
  push:
    branches: [ main ]  # Altere se usar outra branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Instalar Fly.io CLI
        run: curl -L https://fly.io/install.sh | sh
        env:
          FLYCTL_INSTALL: ${{ github.workspace }}/.fly

      - name: Configurar Fly.io
        run: echo "${{ github.workspace }}/.fly/bin" >> $GITHUB_PATH

      - name: Autenticar
        run: fly auth login --access-token ${{ secrets.FLY_API_TOKEN }}

      - name: Deploy
        run: fly deploy -a projeto-copia --remote-only