# Generated by Django 5.2.5 on 2025-09-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_emocoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewConsultaPsicologo',
            fields=[
                ('id_psicologo', models.IntegerField(primary_key=True, serialize=False)),
                ('id_usuario', models.IntegerField(blank=True, null=True)),
                ('nome_psicologo', models.CharField(blank=True, max_length=100, null=True)),
                ('abordagem', models.CharField(blank=True, max_length=100, null=True)),
                ('crp', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('qt_pacientes', models.BigIntegerField(blank=True, null=True)),
                ('ids_pacientes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'view_consulta_psicologo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VwConsultasDetalhes',
            fields=[
                ('id_consulta', models.IntegerField(primary_key=True, serialize=False)),
                ('data_consulta', models.DateField(blank=True, null=True)),
                ('nome_paciente', models.CharField(blank=True, max_length=100, null=True)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('tipo_tratamento', models.CharField(blank=True, max_length=100, null=True)),
                ('nome_psicologo', models.CharField(blank=True, max_length=100, null=True)),
                ('abordagem', models.CharField(blank=True, max_length=100, null=True)),
                ('crp', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'vw_consultas_detalhes',
                'managed': False,
            },
        ),
    ]
