# fly.toml simplificado
app = 'emocoes'
primary_region = 'gig'

[build]
  dockerfile = "Dockerfile"  # ← Apenas esta linha de build, remova o resto

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0