app = 'mix-and-match'
primary_region = 'gru'

[build]
  build_args = {
    BUILDKIT_INLINE_CACHE = "1"
  }

# Serviço do Backend (Django)
[[services]]
  internal_port = 8000
  protocol = "tcp"
  name = "backend"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = 8000

  [[services.http_checks]]
    interval = 10000
    grace_period = "5s"
    method = "get"
    path = "/api/health/"
    protocol = "http"
    timeout = 2000

# Serviço do Frontend
[[services]]
  internal_port = 80
  protocol = "tcp"
  name = "frontend"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.http_checks]]
    interval = 10000
    grace_period = "5s"
    method = "get"
    path = "/"
    protocol = "http"
    timeout = 2000

# Máquina virtual
[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1